package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1



/**
 * Administrateur generated by hbm2java
 */
public class Administrateur  implements java.io.Serializable {


     private int idutilisateur;
     private Utilisateur utilisateur;

    public Administrateur() {
    }

    public Administrateur(Utilisateur utilisateur) {
       this.utilisateur = utilisateur;
    }
   
    public int getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(int idutilisateur) {
        this.idutilisateur = idutilisateur;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }




}


