package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Anneeuniversitaire generated by hbm2java
 */
public class Anneeuniversitaire  implements java.io.Serializable {


     private String anneeuniversitaire;
     private Set<Niveauannee> niveauannees = new HashSet<Niveauannee>(0);

    public Anneeuniversitaire() {
    }

	
    public Anneeuniversitaire(String anneeuniversitaire) {
        this.anneeuniversitaire = anneeuniversitaire;
    }
    public Anneeuniversitaire(String anneeuniversitaire, Set<Niveauannee> niveauannees) {
       this.anneeuniversitaire = anneeuniversitaire;
       this.niveauannees = niveauannees;
    }
   
    public String getAnneeuniversitaire() {
        return this.anneeuniversitaire;
    }
    
    public void setAnneeuniversitaire(String anneeuniversitaire) {
        this.anneeuniversitaire = anneeuniversitaire;
    }
    public Set<Niveauannee> getNiveauannees() {
        return this.niveauannees;
    }
    
    public void setNiveauannees(Set<Niveauannee> niveauannees) {
        this.niveauannees = niveauannees;
    }




}


