package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Demande generated by hbm2java
 */
public class Demande  implements java.io.Serializable {


     private int numd;
     private Enseignant enseignant;
     private Date dated;
     private Set<LigneDemande> ligneDemandes = new HashSet<LigneDemande>(0);

    public Demande() {
    }

	
    public Demande(int numd, Enseignant enseignant) {
        this.numd = numd;
        this.enseignant = enseignant;
    }
    public Demande(int numd, Enseignant enseignant, Date dated, Set<LigneDemande> ligneDemandes) {
       this.numd = numd;
       this.enseignant = enseignant;
       this.dated = dated;
       this.ligneDemandes = ligneDemandes;
    }
   
    public int getNumd() {
        return this.numd;
    }
    
    public void setNumd(int numd) {
        this.numd = numd;
    }
    public Enseignant getEnseignant() {
        return this.enseignant;
    }
    
    public void setEnseignant(Enseignant enseignant) {
        this.enseignant = enseignant;
    }
    public Date getDated() {
        return this.dated;
    }
    
    public void setDated(Date dated) {
        this.dated = dated;
    }
    public Set<LigneDemande> getLigneDemandes() {
        return this.ligneDemandes;
    }
    
    public void setLigneDemandes(Set<LigneDemande> ligneDemandes) {
        this.ligneDemandes = ligneDemandes;
    }




}


