package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Enseignant generated by hbm2java
 */
public class Enseignant  implements java.io.Serializable {


     private int idutilisateur;
     private Utilisateur utilisateur;
     private String grade;
     private String typecontrat;
     private Date dateembauche;
     private Float nbhe;
     private Set<Demande> demandes = new HashSet<Demande>(0);

    public Enseignant() {
    }

	
    public Enseignant(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Enseignant(Utilisateur utilisateur, String grade, String typecontrat, Date dateembauche, Float nbhe, Set<Demande> demandes) {
       this.utilisateur = utilisateur;
       this.grade = grade;
       this.typecontrat = typecontrat;
       this.dateembauche = dateembauche;
       this.nbhe = nbhe;
       this.demandes = demandes;
    }
   
    public int getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(int idutilisateur) {
        this.idutilisateur = idutilisateur;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public String getTypecontrat() {
        return this.typecontrat;
    }
    
    public void setTypecontrat(String typecontrat) {
        this.typecontrat = typecontrat;
    }
    public Date getDateembauche() {
        return this.dateembauche;
    }
    
    public void setDateembauche(Date dateembauche) {
        this.dateembauche = dateembauche;
    }
    public Float getNbhe() {
        return this.nbhe;
    }
    
    public void setNbhe(Float nbhe) {
        this.nbhe = nbhe;
    }
    public Set<Demande> getDemandes() {
        return this.demandes;
    }
    
    public void setDemandes(Set<Demande> demandes) {
        this.demandes = demandes;
    }




}


