package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1



/**
 * LigneDemande generated by hbm2java
 */
public class LigneDemande  implements java.io.Serializable {


     private LigneDemandeId id;
     private Demande demande;
     private Prog prog;
     private Integer nbtp;
     private Integer nbtd;
     private Integer nbc;
     private String etat;

    public LigneDemande() {
    }

	
    public LigneDemande(LigneDemandeId id, Demande demande, Prog prog) {
        this.id = id;
        this.demande = demande;
        this.prog = prog;
    }
    public LigneDemande(LigneDemandeId id, Demande demande, Prog prog, Integer nbtp, Integer nbtd, Integer nbc, String etat) {
       this.id = id;
       this.demande = demande;
       this.prog = prog;
       this.nbtp = nbtp;
       this.nbtd = nbtd;
       this.nbc = nbc;
       this.etat = etat;
    }
   
    public LigneDemandeId getId() {
        return this.id;
    }
    
    public void setId(LigneDemandeId id) {
        this.id = id;
    }
    public Demande getDemande() {
        return this.demande;
    }
    
    public void setDemande(Demande demande) {
        this.demande = demande;
    }
    public Prog getProg() {
        return this.prog;
    }
    
    public void setProg(Prog prog) {
        this.prog = prog;
    }
    public Integer getNbtp() {
        return this.nbtp;
    }
    
    public void setNbtp(Integer nbtp) {
        this.nbtp = nbtp;
    }
    public Integer getNbtd() {
        return this.nbtd;
    }
    
    public void setNbtd(Integer nbtd) {
        this.nbtd = nbtd;
    }
    public Integer getNbc() {
        return this.nbc;
    }
    
    public void setNbc(Integer nbc) {
        this.nbc = nbc;
    }
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }




}


