package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1



/**
 * LigneDemandeId generated by hbm2java
 */
public class LigneDemandeId  implements java.io.Serializable {


     private String section;
 
     private String libelle;
     private int numd;

    public LigneDemandeId() {
    }

    public LigneDemandeId(String section,  String libelle, int numd) {
       this.section = section;
       
       this.libelle = libelle;
       this.numd = numd;
    }
   
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
   
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public int getNumd() {
        return this.numd;
    }
    
    public void setNumd(int numd) {
        this.numd = numd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LigneDemandeId) ) return false;
		 LigneDemandeId castOther = ( LigneDemandeId ) other; 
         
		 return ( (this.getSection()==castOther.getSection()) || ( this.getSection()!=null && castOther.getSection()!=null && this.getSection().equals(castOther.getSection()) ) )
 && ( (this.getLibelle()==castOther.getLibelle()) || ( this.getLibelle()!=null && castOther.getLibelle()!=null && this.getLibelle().equals(castOther.getLibelle()) ) )
 && (this.getNumd()==castOther.getNumd());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSection() == null ? 0 : this.getSection().hashCode() );
        
         result = 37 * result + ( getLibelle() == null ? 0 : this.getLibelle().hashCode() );
         result = 37 * result + this.getNumd();
         return result;
   }   


}


