package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Matiere generated by hbm2java
 */
public class Matiere  implements java.io.Serializable {


     private String libelle;
     private Set<Prog> progs = new HashSet<Prog>(0);

    public Matiere() {
    }

	
    public Matiere(String libelle) {
        this.libelle = libelle;
    }
    public Matiere(String libelle, Set<Prog> progs) {
       this.libelle = libelle;
       this.progs = progs;
    }
   
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public Set<Prog> getProgs() {
        return this.progs;
    }
    
    public void setProgs(Set<Prog> progs) {
        this.progs = progs;
    }




}


