package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1



/**
 * Niveauannee generated by hbm2java
 */
public class Niveauannee  implements java.io.Serializable {


     private NiveauanneeId id;
     private Anneeuniversitaire anneeuniversitaire;
     private Niveau niveau;
     private Short nbgpec;
     private Short nbgpetd;
     private Short nbgpetp;

    public Niveauannee() {
    }

	
    public Niveauannee(NiveauanneeId id, Anneeuniversitaire anneeuniversitaire, Niveau niveau) {
        this.id = id;
        this.anneeuniversitaire = anneeuniversitaire;
        this.niveau = niveau;
    }
    public Niveauannee(NiveauanneeId id, Anneeuniversitaire anneeuniversitaire, Niveau niveau, Short nbgpec, Short nbgpetd, Short nbgpetp) {
       this.id = id;
       this.anneeuniversitaire = anneeuniversitaire;
       this.niveau = niveau;
       this.nbgpec = nbgpec;
       this.nbgpetd = nbgpetd;
       this.nbgpetp = nbgpetp;
    }
   
    public NiveauanneeId getId() {
        return this.id;
    }
    
    public void setId(NiveauanneeId id) {
        this.id = id;
    }
    public Anneeuniversitaire getAnneeuniversitaire() {
        return this.anneeuniversitaire;
    }
    
    public void setAnneeuniversitaire(Anneeuniversitaire anneeuniversitaire) {
        this.anneeuniversitaire = anneeuniversitaire;
    }
    public Niveau getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(Niveau niveau) {
        this.niveau = niveau;
    }
    public Short getNbgpec() {
        return this.nbgpec;
    }
    
    public void setNbgpec(Short nbgpec) {
        this.nbgpec = nbgpec;
    }
    public Short getNbgpetd() {
        return this.nbgpetd;
    }
    
    public void setNbgpetd(Short nbgpetd) {
        this.nbgpetd = nbgpetd;
    }
    public Short getNbgpetp() {
        return this.nbgpetp;
    }
    
    public void setNbgpetp(Short nbgpetp) {
        this.nbgpetp = nbgpetp;
    }




}


