package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1



/**
 * ProgId generated by hbm2java
 */
public class ProgId  implements java.io.Serializable {


     private String section;
     private int codem;
     private String libelle;

    public ProgId() {
    }

    public ProgId(String section, int codem, String libelle) {
       this.section = section;
       this.codem = codem;
       this.libelle = libelle;
    }
   
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
    public int getCodem() {
        return this.codem;
    }
    
    public void setCodem(int codem) {
        this.codem = codem;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProgId) ) return false;
		 ProgId castOther = ( ProgId ) other; 
         
		 return ( (this.getSection()==castOther.getSection()) || ( this.getSection()!=null && castOther.getSection()!=null && this.getSection().equals(castOther.getSection()) ) )
 && (this.getCodem()==castOther.getCodem())
 && ( (this.getLibelle()==castOther.getLibelle()) || ( this.getLibelle()!=null && castOther.getLibelle()!=null && this.getLibelle().equals(castOther.getLibelle()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSection() == null ? 0 : this.getSection().hashCode() );
         result = 37 * result + this.getCodem();
         result = 37 * result + ( getLibelle() == null ? 0 : this.getLibelle().hashCode() );
         return result;
   }   


}


