package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Prog generated by hbm2java
 */
public class Prog  implements java.io.Serializable {


     private ProgId id;
     private Matiere matiere;
     private Niveau niveau;
     private Double nbhc;
     private Double nbhtp;
     private Double nbhtd;
     private Set<LigneDemande> ligneDemandes = new HashSet<LigneDemande>(0);

    public Prog() {
    }

	
    public Prog(ProgId id, Matiere matiere, Niveau niveau) {
        this.id = id;
        this.matiere = matiere;
        this.niveau = niveau;
    }
    public Prog(ProgId id, Matiere matiere, Niveau niveau, Double nbhc, Double nbhtp, Double nbhtd, Set<LigneDemande> ligneDemandes) {
       this.id = id;
       this.matiere = matiere;
       this.niveau = niveau;
       this.nbhc = nbhc;
       this.nbhtp = nbhtp;
       this.nbhtd = nbhtd;
       this.ligneDemandes = ligneDemandes;
    }
   
    public ProgId getId() {
        return this.id;
    }
    
    public void setId(ProgId id) {
        this.id = id;
    }
    public Matiere getMatiere() {
        return this.matiere;
    }
    
    public void setMatiere(Matiere matiere) {
        this.matiere = matiere;
    }
    public Niveau getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(Niveau niveau) {
        this.niveau = niveau;
    }
    public Double getNbhc() {
        return this.nbhc;
    }
    
    public void setNbhc(Double nbhc) {
        this.nbhc = nbhc;
    }
    public Double getNbhtp() {
        return this.nbhtp;
    }
    
    public void setNbhtp(Double nbhtp) {
        this.nbhtp = nbhtp;
    }
    public Double getNbhtd() {
        return this.nbhtd;
    }
    
    public void setNbhtd(Double nbhtd) {
        this.nbhtd = nbhtd;
    }
    public Set<LigneDemande> getLigneDemandes() {
        return this.ligneDemandes;
    }
    
    public void setLigneDemandes(Set<LigneDemande> ligneDemandes) {
        this.ligneDemandes = ligneDemandes;
    }




}


