package beans;
// Generated 7 juin 2015 23:46:30 by Hibernate Tools 4.3.1



/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private int idutilisateur;
     private String nom;
     private String prenom;
     private String password;
     private Administrateur administrateur;
     private Enseignant enseignant;

    public Utilisateur() {
    }

	
    public Utilisateur(int idutilisateur) {
        this.idutilisateur = idutilisateur;
    }
    public Utilisateur(int idutilisateur, String nom, String prenom, String password, Administrateur administrateur, Enseignant enseignant) {
       this.idutilisateur = idutilisateur;
       this.nom = nom;
       this.prenom = prenom;
       this.password = password;
       this.administrateur = administrateur;
       this.enseignant = enseignant;
    }
   
    public int getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(int idutilisateur) {
        this.idutilisateur = idutilisateur;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Administrateur getAdministrateur() {
        return this.administrateur;
    }
    
    public void setAdministrateur(Administrateur administrateur) {
        this.administrateur = administrateur;
    }
    public Enseignant getEnseignant() {
        return this.enseignant;
    }
    
    public void setEnseignant(Enseignant enseignant) {
        this.enseignant = enseignant;
    }




}


